name = "design-template"
version = "0.1.0"
[dependencies]
JITX3 = { path = "{SLM_ROOT}/JITX3" }
jlc-pcb = { git = "JITx-Inc/jlc-pcb", version = "0.3.2" }
TI-vreg = { git = "JITx-Inc/TI-VREG", version = "0.4.0" }
connectors = { git = "JITx-Inc/connectors", version = "0.4.1" }